# Generated by Django 3.0.3 on 2020-07-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('bid', models.PositiveIntegerField()),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
